baseURL = 'https://redtrilliumgardens.com'
languageCode = 'en-us'
title = 'Red Trillium Gardens'

[module]
  [[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke'

[markup.goldmark.renderer]
  unsafe = true

[params]
  text_color = ""
  author = "Lise Fracalossi"
  favicon = "images/favicon.ico"
  description = "Red Trillium Gardens is a native plant nursery opening for business in Lunenburg, MA in Spring 2024."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  site_logo = "images/rtg-logo-initials200x200.png"
  custom_css = ["custom.css"]